n = str(input('Digite seu nome completo: ')).strip().title()
nome = n.split()
print('Muito prazer em te conhecer!')
print('Seu Primeiro nome é: {}'.format(nome[0]))
print('Seu último nome é: {}'.format(nome[len(nome)-1]))
